#修改端口号
server:
  port: 8080
  #这只logging日志级别
logging:
  level:
    wen.tian: debug
    # org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zjyg?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
mybatis:
  type-aliases-package: wen.tian.pojo
